title = "tcp.ac config"

[global]
debug      = true

[http]
baseurl    = "http://192.168.69.1/"
bindip     = "192.168.69.1"
port       = 80

[img]
uidsize    = 4
delkeysize = 12

[files]
data       = "/etc/tcpac/data/"
logs	   = "/etc/tcpac/logs/"
