title = "tcp.ac config"

[global]
debug      = false

[http]
baseurl    = "http://127.0.0.1:8080/"
bindip     = "127.0.0.1"
port       = 8080

[img]
uidsize    = 6
delkeysize = 24

[files]
data       = "../data/"
logs	   = "../logs/"
