title = "tcp.ac config"

[global]
debug      = true
uidsize    = 5
delkeysize = 12

[http]
baseurl    = "http://127.0.0.1:8080/"
bindip     = "127.0.0.1"
port       = 8080

[txt]
# string: port to listen on for termbin clone
port       = "9988"

[files]
data       = "./data/"
logs	   = "./logs/"
sizelimit  = 48
