[data]
directory = '.data'
max_key_size_mb = 10
max_value_size_mb = 20

[http]
bind_addr = '127.0.0.1'
bind_port = '8080'
unix_socket_path = '/var/run/tcp.ac'
unix_socket_permissions = 420
use_unix_socket = false

[logger]
debug = true
directory = '.logs'
nocolor = false
trace = false
use_date_filename = true

[other]
delete_key_size = 12
termbin_listen = '127.0.0.1:9999'
uid_size = 5

